//----------------------
// <auto-generated>
//     Generated using the NJsonSchema v10.1.21.0 (Newtonsoft.Json v9.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------

namespace SchemaConfiguration
{
    #pragma warning disable // Disable all warnings

    
    public partial class AbstractDataRule 
    {
        [Newtonsoft.Json.JsonProperty("Container", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string Container { get; set; }
    
        [Newtonsoft.Json.JsonProperty("ReadAccess", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public AbstractDataRole ReadAccess { get; set; }
    
        [Newtonsoft.Json.JsonProperty("WriteAccess", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public AbstractDataRole WriteAccess { get; set; }
    
    
    }
    
    
    public enum AbstractDataRole
    {
        None = 0,
    
        Owner = 1,
    
        Server = 2,
    
        Other = 4,
    
    }
    
    
    public partial class ServiceParameters 
    {
    
    }
    
    
    public partial class AbstractDataServiceParameters : ServiceParameters
    {
        [Newtonsoft.Json.JsonProperty("AbstractDataRules", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public System.Collections.Generic.ICollection<AbstractDataRule> AbstractDataRules { get; set; }
    
    
    }
}