// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: example.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Sample {

  /// <summary>Holder for reflection information generated from example.proto</summary>
  public static partial class ExampleReflection {

    #region Descriptor
    /// <summary>File descriptor for example.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ExampleReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg1leGFtcGxlLnByb3RvEgh0dXRvcmlhbBofZ29vZ2xlL3Byb3RvYnVmL3Rp",
            "bWVzdGFtcC5wcm90byL2AwoPT2ZmZXJQYXJhbWV0ZXJzEk0KEk9mZmVyQWNj",
            "ZXNzUm9sZU1hcBgBIAMoCzIxLnR1dG9yaWFsLk9mZmVyUGFyYW1ldGVycy5P",
            "ZmZlckFjY2Vzc1JvbGVNYXBFbnRyeRIgChhTdGVhbVRyYW5zYWN0aW9uc0Vu",
            "YWJsZWQYAiABKAgSJwofRGlnaXRhbFJpdmVyVHJhbnNhY3Rpb25zRW5hYmxl",
            "ZBgDIAEoCBIlCh1Hb29nbGVQbGF5VHJhbnNhY3Rpb25zRW5hYmxlZBgEIAEo",
            "CBIjChtBcHBTdG9yZVRyYW5zYWN0aW9uc0VuYWJsZWQYBSABKAgSKgoiRGlz",
            "YWJsZUFwcFN0b3JlUmVjZWlwdFZlcmlmaWNhdGlvbhgGIAEoCBIwCihEaXNh",
            "YmxlR29vZ2xlUGxheVRyYW5zYWN0aW9uVmVyaWZpY2F0aW9uGAcgASgIEkcK",
            "I01hc3NPZmZlcnNDYWNoZUludmFsaWRhdGlvbkludGVydmFsGAggASgLMhou",
            "Z29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcBpWChdPZmZlckFjY2Vzc1JvbGVN",
            "YXBFbnRyeRILCgNrZXkYASABKAUSKgoFdmFsdWUYAiABKA4yGy50dXRvcmlh",
            "bC5TZXJ2aWNlQWNjZXNzUm9sZToCOAEq6QEKEVNlcnZpY2VBY2Nlc3NSb2xl",
            "EgkKBU5vZG5lEAASCQoFRGVidWcQARIJCgVHdWVzdBACEgwKCFNlcnZpY2Vz",
            "EAQSDgoKR2FtZUNsaWVudBAIEhMKD0RlZGljYXRlZFNlcnZlchAQEggKBEdh",
            "bWUQGBIMCghEc21BZ2VudBAgEg0KCVdlYlBvcnRhbBBAEg8KCkJvdE1hbmFn",
            "ZXIQgAESEgoNQ3Jhc2hBbmFseXplchCAAhIJCgRUb29sELACEggKA0VTTBCA",
            "BBINCghCSUxvb2t1cBCACBIQCgtEaWFnbm9zdGljcxCAEEIJqgIGU2FtcGxl",
            "YgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.TimestampReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Sample.ServiceAccessRole), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Sample.OfferParameters), global::Sample.OfferParameters.Parser, new[]{ "OfferAccessRoleMap", "SteamTransactionsEnabled", "DigitalRiverTransactionsEnabled", "GooglePlayTransactionsEnabled", "AppStoreTransactionsEnabled", "DisableAppStoreReceiptVerification", "DisableGooglePlayTransactionVerification", "MassOffersCacheInvalidationInterval" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { null, })
          }));
    }
    #endregion

  }
  #region Enums
  /// <summary>
  ///wfefwefwefwef
  /// </summary>
  public enum ServiceAccessRole {
    [pbr::OriginalName("Nodne")] Nodne = 0,
    [pbr::OriginalName("Debug")] Debug = 1,
    [pbr::OriginalName("Guest")] Guest = 2,
    [pbr::OriginalName("Services")] Services = 4,
    [pbr::OriginalName("GameClient")] GameClient = 8,
    [pbr::OriginalName("DedicatedServer")] DedicatedServer = 16,
    [pbr::OriginalName("Game")] Game = 24,
    [pbr::OriginalName("DsmAgent")] DsmAgent = 32,
    [pbr::OriginalName("WebPortal")] WebPortal = 64,
    [pbr::OriginalName("BotManager")] BotManager = 128,
    [pbr::OriginalName("CrashAnalyzer")] CrashAnalyzer = 256,
    [pbr::OriginalName("Tool")] Tool = 304,
    [pbr::OriginalName("ESL")] Esl = 512,
    [pbr::OriginalName("BILookup")] Bilookup = 1024,
    [pbr::OriginalName("Diagnostics")] Diagnostics = 2048,
  }

  #endregion

  #region Messages
  public sealed partial class OfferParameters : pb::IMessage<OfferParameters> {
    private static readonly pb::MessageParser<OfferParameters> _parser = new pb::MessageParser<OfferParameters>(() => new OfferParameters());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<OfferParameters> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Sample.ExampleReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public OfferParameters() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public OfferParameters(OfferParameters other) : this() {
      offerAccessRoleMap_ = other.offerAccessRoleMap_.Clone();
      steamTransactionsEnabled_ = other.steamTransactionsEnabled_;
      digitalRiverTransactionsEnabled_ = other.digitalRiverTransactionsEnabled_;
      googlePlayTransactionsEnabled_ = other.googlePlayTransactionsEnabled_;
      appStoreTransactionsEnabled_ = other.appStoreTransactionsEnabled_;
      disableAppStoreReceiptVerification_ = other.disableAppStoreReceiptVerification_;
      disableGooglePlayTransactionVerification_ = other.disableGooglePlayTransactionVerification_;
      massOffersCacheInvalidationInterval_ = other.massOffersCacheInvalidationInterval_ != null ? other.massOffersCacheInvalidationInterval_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public OfferParameters Clone() {
      return new OfferParameters(this);
    }

    /// <summary>Field number for the "OfferAccessRoleMap" field.</summary>
    public const int OfferAccessRoleMapFieldNumber = 1;
    private static readonly pbc::MapField<int, global::Sample.ServiceAccessRole>.Codec _map_offerAccessRoleMap_codec
        = new pbc::MapField<int, global::Sample.ServiceAccessRole>.Codec(pb::FieldCodec.ForInt32(8, 0), pb::FieldCodec.ForEnum(16, x => (int) x, x => (global::Sample.ServiceAccessRole) x, global::Sample.ServiceAccessRole.Nodne), 10);
    private readonly pbc::MapField<int, global::Sample.ServiceAccessRole> offerAccessRoleMap_ = new pbc::MapField<int, global::Sample.ServiceAccessRole>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::MapField<int, global::Sample.ServiceAccessRole> OfferAccessRoleMap {
      get { return offerAccessRoleMap_; }
    }

    /// <summary>Field number for the "SteamTransactionsEnabled" field.</summary>
    public const int SteamTransactionsEnabledFieldNumber = 2;
    private bool steamTransactionsEnabled_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool SteamTransactionsEnabled {
      get { return steamTransactionsEnabled_; }
      set {
        steamTransactionsEnabled_ = value;
      }
    }

    /// <summary>Field number for the "DigitalRiverTransactionsEnabled" field.</summary>
    public const int DigitalRiverTransactionsEnabledFieldNumber = 3;
    private bool digitalRiverTransactionsEnabled_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool DigitalRiverTransactionsEnabled {
      get { return digitalRiverTransactionsEnabled_; }
      set {
        digitalRiverTransactionsEnabled_ = value;
      }
    }

    /// <summary>Field number for the "GooglePlayTransactionsEnabled" field.</summary>
    public const int GooglePlayTransactionsEnabledFieldNumber = 4;
    private bool googlePlayTransactionsEnabled_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool GooglePlayTransactionsEnabled {
      get { return googlePlayTransactionsEnabled_; }
      set {
        googlePlayTransactionsEnabled_ = value;
      }
    }

    /// <summary>Field number for the "AppStoreTransactionsEnabled" field.</summary>
    public const int AppStoreTransactionsEnabledFieldNumber = 5;
    private bool appStoreTransactionsEnabled_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool AppStoreTransactionsEnabled {
      get { return appStoreTransactionsEnabled_; }
      set {
        appStoreTransactionsEnabled_ = value;
      }
    }

    /// <summary>Field number for the "DisableAppStoreReceiptVerification" field.</summary>
    public const int DisableAppStoreReceiptVerificationFieldNumber = 6;
    private bool disableAppStoreReceiptVerification_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool DisableAppStoreReceiptVerification {
      get { return disableAppStoreReceiptVerification_; }
      set {
        disableAppStoreReceiptVerification_ = value;
      }
    }

    /// <summary>Field number for the "DisableGooglePlayTransactionVerification" field.</summary>
    public const int DisableGooglePlayTransactionVerificationFieldNumber = 7;
    private bool disableGooglePlayTransactionVerification_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool DisableGooglePlayTransactionVerification {
      get { return disableGooglePlayTransactionVerification_; }
      set {
        disableGooglePlayTransactionVerification_ = value;
      }
    }

    /// <summary>Field number for the "MassOffersCacheInvalidationInterval" field.</summary>
    public const int MassOffersCacheInvalidationIntervalFieldNumber = 8;
    private global::Google.Protobuf.WellKnownTypes.Timestamp massOffersCacheInvalidationInterval_;
    /// <summary>
    ///BLABLABLA descrption
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Google.Protobuf.WellKnownTypes.Timestamp MassOffersCacheInvalidationInterval {
      get { return massOffersCacheInvalidationInterval_; }
      set {
        massOffersCacheInvalidationInterval_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as OfferParameters);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(OfferParameters other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!OfferAccessRoleMap.Equals(other.OfferAccessRoleMap)) return false;
      if (SteamTransactionsEnabled != other.SteamTransactionsEnabled) return false;
      if (DigitalRiverTransactionsEnabled != other.DigitalRiverTransactionsEnabled) return false;
      if (GooglePlayTransactionsEnabled != other.GooglePlayTransactionsEnabled) return false;
      if (AppStoreTransactionsEnabled != other.AppStoreTransactionsEnabled) return false;
      if (DisableAppStoreReceiptVerification != other.DisableAppStoreReceiptVerification) return false;
      if (DisableGooglePlayTransactionVerification != other.DisableGooglePlayTransactionVerification) return false;
      if (!object.Equals(MassOffersCacheInvalidationInterval, other.MassOffersCacheInvalidationInterval)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= OfferAccessRoleMap.GetHashCode();
      if (SteamTransactionsEnabled != false) hash ^= SteamTransactionsEnabled.GetHashCode();
      if (DigitalRiverTransactionsEnabled != false) hash ^= DigitalRiverTransactionsEnabled.GetHashCode();
      if (GooglePlayTransactionsEnabled != false) hash ^= GooglePlayTransactionsEnabled.GetHashCode();
      if (AppStoreTransactionsEnabled != false) hash ^= AppStoreTransactionsEnabled.GetHashCode();
      if (DisableAppStoreReceiptVerification != false) hash ^= DisableAppStoreReceiptVerification.GetHashCode();
      if (DisableGooglePlayTransactionVerification != false) hash ^= DisableGooglePlayTransactionVerification.GetHashCode();
      if (massOffersCacheInvalidationInterval_ != null) hash ^= MassOffersCacheInvalidationInterval.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      offerAccessRoleMap_.WriteTo(output, _map_offerAccessRoleMap_codec);
      if (SteamTransactionsEnabled != false) {
        output.WriteRawTag(16);
        output.WriteBool(SteamTransactionsEnabled);
      }
      if (DigitalRiverTransactionsEnabled != false) {
        output.WriteRawTag(24);
        output.WriteBool(DigitalRiverTransactionsEnabled);
      }
      if (GooglePlayTransactionsEnabled != false) {
        output.WriteRawTag(32);
        output.WriteBool(GooglePlayTransactionsEnabled);
      }
      if (AppStoreTransactionsEnabled != false) {
        output.WriteRawTag(40);
        output.WriteBool(AppStoreTransactionsEnabled);
      }
      if (DisableAppStoreReceiptVerification != false) {
        output.WriteRawTag(48);
        output.WriteBool(DisableAppStoreReceiptVerification);
      }
      if (DisableGooglePlayTransactionVerification != false) {
        output.WriteRawTag(56);
        output.WriteBool(DisableGooglePlayTransactionVerification);
      }
      if (massOffersCacheInvalidationInterval_ != null) {
        output.WriteRawTag(66);
        output.WriteMessage(MassOffersCacheInvalidationInterval);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += offerAccessRoleMap_.CalculateSize(_map_offerAccessRoleMap_codec);
      if (SteamTransactionsEnabled != false) {
        size += 1 + 1;
      }
      if (DigitalRiverTransactionsEnabled != false) {
        size += 1 + 1;
      }
      if (GooglePlayTransactionsEnabled != false) {
        size += 1 + 1;
      }
      if (AppStoreTransactionsEnabled != false) {
        size += 1 + 1;
      }
      if (DisableAppStoreReceiptVerification != false) {
        size += 1 + 1;
      }
      if (DisableGooglePlayTransactionVerification != false) {
        size += 1 + 1;
      }
      if (massOffersCacheInvalidationInterval_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(MassOffersCacheInvalidationInterval);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(OfferParameters other) {
      if (other == null) {
        return;
      }
      offerAccessRoleMap_.Add(other.offerAccessRoleMap_);
      if (other.SteamTransactionsEnabled != false) {
        SteamTransactionsEnabled = other.SteamTransactionsEnabled;
      }
      if (other.DigitalRiverTransactionsEnabled != false) {
        DigitalRiverTransactionsEnabled = other.DigitalRiverTransactionsEnabled;
      }
      if (other.GooglePlayTransactionsEnabled != false) {
        GooglePlayTransactionsEnabled = other.GooglePlayTransactionsEnabled;
      }
      if (other.AppStoreTransactionsEnabled != false) {
        AppStoreTransactionsEnabled = other.AppStoreTransactionsEnabled;
      }
      if (other.DisableAppStoreReceiptVerification != false) {
        DisableAppStoreReceiptVerification = other.DisableAppStoreReceiptVerification;
      }
      if (other.DisableGooglePlayTransactionVerification != false) {
        DisableGooglePlayTransactionVerification = other.DisableGooglePlayTransactionVerification;
      }
      if (other.massOffersCacheInvalidationInterval_ != null) {
        if (massOffersCacheInvalidationInterval_ == null) {
          MassOffersCacheInvalidationInterval = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        MassOffersCacheInvalidationInterval.MergeFrom(other.MassOffersCacheInvalidationInterval);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            offerAccessRoleMap_.AddEntriesFrom(input, _map_offerAccessRoleMap_codec);
            break;
          }
          case 16: {
            SteamTransactionsEnabled = input.ReadBool();
            break;
          }
          case 24: {
            DigitalRiverTransactionsEnabled = input.ReadBool();
            break;
          }
          case 32: {
            GooglePlayTransactionsEnabled = input.ReadBool();
            break;
          }
          case 40: {
            AppStoreTransactionsEnabled = input.ReadBool();
            break;
          }
          case 48: {
            DisableAppStoreReceiptVerification = input.ReadBool();
            break;
          }
          case 56: {
            DisableGooglePlayTransactionVerification = input.ReadBool();
            break;
          }
          case 66: {
            if (massOffersCacheInvalidationInterval_ == null) {
              MassOffersCacheInvalidationInterval = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(MassOffersCacheInvalidationInterval);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
