// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: example2.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Sample {

  /// <summary>Holder for reflection information generated from example2.proto</summary>
  public static partial class Example2Reflection {

    #region Descriptor
    /// <summary>File descriptor for example2.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static Example2Reflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg5leGFtcGxlMi5wcm90bxIIdHV0b3JpYWwaH2dvb2dsZS9wcm90b2J1Zi90",
            "aW1lc3RhbXAucHJvdG8qbgoMT2ZmZXJBY2xUeXBlEggKBE5vbmUQABIICgRH",
            "YW1lEAESEwoPRGVkaWNhdGVkU2VydmVyEAISDQoJV2ViUG9ydGFsEAQSDAoI",
            "U2VydmljZXMQCBIMCghJbnRlcm5hbBAOEgoKBlB1YmxpYxAPQgmqAgZTYW1w",
            "bGViBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.TimestampReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Sample.OfferAclType), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum OfferAclType {
    [pbr::OriginalName("None")] None = 0,
    [pbr::OriginalName("Game")] Game = 1,
    /// <summary>
    ///blablabla
    /// </summary>
    [pbr::OriginalName("DedicatedServer")] DedicatedServer = 2,
    [pbr::OriginalName("WebPortal")] WebPortal = 4,
    [pbr::OriginalName("Services")] Services = 8,
    [pbr::OriginalName("Internal")] Internal = 14,
    [pbr::OriginalName("Public")] Public = 15,
  }

  #endregion

}

#endregion Designer generated code
